config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :problems
  root to: 'pages#home'

  get 'pages/discussion'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  validates_presence_of :name, :phone_number, :time

  after_create :reminder

  # config.time_zone = 'Mountain Time (US & Canada)'

  def reminder
    @twilio_number = ENV['TWILIO_PHONE_NUMBER']
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    @client = Twilio::REST::Client.new account_sid, ENV['TWILIO_AUTH_TOKEN']
    time_str = ((self.time).localtime).strftime("%I:%M%p on %b. %d, %Y")
    reminder = "Hi #{self.name}. Just a reminder that you have an appointment coming up at #{time_str}."
    message = @client.api.account(account_sid).messages.create(
      :from => @twilio_number,
      :to => self.phone_number,
      :body => reminder,
    )
  end

  def when_to_run
    minutes_before_appointment = 1.day
    time - minutes_before_appointment
  end

  handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }

end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :email, :id
end

app/models/problem.rb
class Problem < ApplicationRecord


  validates_presence_of :title, :description, :body

end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :author], multiple: true)                                       ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :phone_number

  PHONE_REGEX = /\A[0-9]*\Z/

  validates_format_of :phone_number, with: PHONE_REGEX

  validates :phone_number, length: { is: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include CurrentUserConcern
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /appointments
  def index
    @appointments = Appointment.all
    if @appointments.length.zero?
      flash[:alert] = 'You have no appointments. Create one now to get started.'
    end
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    Time.zone = appointment_params[:time_zone]
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    redirect_to appointments_url, notice: 'Appointment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def appointment_params
      params.require(:appointment).permit(:name, :phone_number, :time)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    guest = GuestUser.new
    guest.name = "Guest User"
    guest.email = "guest@example.com"
    guest.phone_number = '4444444444'
    guest
  end

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern


  included do
    before_action :configure_permitted_parameters, if: :devise_controller?    
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def discussion
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]
  layout 'problem'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, author: :all, admin: :all

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:title, :description, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language || :ruby).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/appointments/_form.html.erb
<%= form_for @appointment, :html => { :class => "form-horizontal appointment" } do |f| %>

  <% if @appointment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone_number) %>
  </div>
  <div class="form-group">
    <%= f.label :time, "Time and Date", :class => 'control-label col-lg-2' %>
    <!-- Rails expects time_select when dealing with ActiveRecord forms -->
    <div class="col-lg-2">
      <%= time_select :appointment, :time, {:class => "form-control" } %>
    </div>
    <div class="col-lg-4">
      <%= date_select :appointment, :time, {:class => "form-control" } %>
    </div>
    <%=f.error_span(:time) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                appointments_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= link_to appointment.id, appointment_path(appointment) %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.phone_number %></td>
        <td><%= appointment.time %></td>
        <td><%=l appointment.created_at %></td>
        <td>
          <%= link_to "Edit", 
                      edit_appointment_path(appointment), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Delete",
                      appointment_path(appointment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @appointment.phone_number %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funfun</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/problem.html.erb
<!doctype html>
<html lang="en">
  <head>
    
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Problems</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'problems', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/problem_nav' %>

    <%= render 'shared/problem_mast' %>

    <%= yield %>

    <%= render 'shared/problem_footer' %>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  
  </body>
</html>

app/views/pages/discussion.html.erb
<h1>Pages#discussion</h1>
<p>Find me in app/views/pages/discussion.html.erb</p>

app/views/pages/home.html.erb
<h1></h1>

app/views/problems/_form.html.erb
<div class='col-md-8'> 
  <%= form_with(model: problem, local: true) do |form| %>
    <% if problem.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

        <ul>
        <% problem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
    </div>

    <div class="form-group">
      <%= form.text_field :description, class: 'form-control', placeholder: 'Description' %>
    </div>

    <div class="form-group">
      <%= form.text_area :body, class: 'form-control', rows: 15, placeholder: 'Content' %>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class: 'actions' %>
    </div>
    
  <% end %>
</div>

  
  

app/views/problems/_problem.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to problem.title.upcase, problem %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(problem.created_at, Time.now) %> ago</p>
  
  <p>
    <%= markdown blog.body %>
  </p>
  
</div>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<main role="main" class="container">

  <div class="row">

    <div class="col-sm-8 blog-main">
      <% @problems.each do |problem| %>
        <div class="blog-post">
          <h2 class="blog-post-title"><%= link_to problem.title, problem_path(problem) %></h2>
          <p class="blog-post-meta">Published <%= distance_of_time_in_words(problem.created_at, Time.now) %> ago</p>

          <p>
            <%= markdown problem.body %>
          </p>
        </div><!-- /.blog-post -->
      <% end %> 

      <div class='form-group'>
        <%= link_to "Create New", new_problem_path, class: 'btn btn-primary' %>
      </div>
    </div><!-- /.blog-main -->

    <aside class="col-sm-3 ml-sm-auto blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <h4>About</h4>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>
      <div class="sidebar-module">
        <h4>Archives</h4>
        <ol class="list-unstyled">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>
      <div class="sidebar-module">
        <h4>Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main><!-- /.container -->

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Back', problems_path, class: 'btn btn-primary' %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-8 blog-main">

  <h2><%= @problem.title %></h2>
  
  <p>
    <%= @problem.description %>
  </p>

  <div class="card">
    <%= markdown @problem.body %>
  </div>

  <%= link_to 'Edit', edit_problem_path(@problem), class: 'btn btn-primary' %> |
  <%= link_to 'Back', problems_path, class: 'btn btn-primary' %>

</div>

app/views/shared/_nav.html.erb
<div>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Discussion', pages_discussion_path %>
  <%= link_to 'Problems', problems_path %>
  <%= link_to 'Appointments', appointments_path %>
  <% if current_user.is_a?(GuestUser) %>
    <%= link_to 'Login', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
  <% else %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <%= link_to 'Edit', edit_user_registration_path %>
  <% end %>
</div>        

app/views/shared/_problem_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_problem_mast.html.erb
<header>
  <div class="blog-header">
    <div class="container">
      <h1 class="blog-title">Coding Problems</h1>
      <p class="lead blog-description">Try your hand at a problem or write one for others.</p>
    </div>
  </div>
</header>

app/views/shared/_problem_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav">
      <%= link_to 'Home', root_path, class: 'nav-link active' %>
      <%= link_to 'Discussion', pages_discussion_path, class: 'nav-link' %>
      <%= link_to 'Problems', problems_path, class: 'nav-link' %>
      <% if current_user.is_a?(GuestUser) %>
        <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
      <% else %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
      <% end %>
    </nav>
  </div>
</div>

  
  
  